global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'opensearch'
    static_configs:
      - targets: ['opensearch-node1:9200', 'opensearch-node2:9200', 'opensearch-node3:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'opensearch-dashboards'
    static_configs:
      - targets: ['opensearch-dashboards:5601']
    metrics_path: '/api/stats'
    scrape_interval: 30s
