apiVersion: v1
kind: Service
metadata:
  name: opensearch-master
  namespace: opensearch
spec:
  type: NodePort
  selector:
    app: opensearch-master
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    nodePort: 30920
  - name: transport
    port: 9300
    targetPort: 9300
  - name: metrics
    port: 9600
    targetPort: 9600
